export type ComponentCategory =
  | "Forms"
  | "Layout"
  | "Navigation"
  | "Overlay"
  | "Feedback"
  | "Display";

export type ComponentStatus = "Stable" | "Beta" | "New" | "Deprecated";

export interface ComponentItem {
  id: string;
  name: string;
  description: string;
  category: ComponentCategory;
  status: ComponentStatus;
  path: string;
}

export const componentsData: ComponentItem[] = [
  // ─── Forms ───────────────────────────────────────────────
  {
    id: "button",
    name: "Button",
    description: "사용자의 클릭 상호작용을 유도하는 핵심 액션 컴포넌트.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-button--docs",
  },
  {
    id: "button-group",
    name: "ButtonGroup",
    description: "여러 버튼을 하나의 그룹으로 묶어 관련 액션을 표현.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-buttongroup--docs",
  },
  {
    id: "checkbox",
    name: "Checkbox",
    description: "단일 또는 복수 항목을 선택할 수 있는 체크박스.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-checkbox--docs",
  },
  {
    id: "date-picker",
    name: "DatePicker",
    description: "캘린더 팝업을 통해 날짜를 선택하는 입력 컴포넌트.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-datepicker--docs",
  },
  {
    id: "field",
    name: "Field",
    description: "레이블, 설명, 에러 메시지를 포함한 폼 필드 래퍼.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-field--docs",
  },
  {
    id: "form",
    name: "Form",
    description: "React Hook Form과 통합된 유효성 검사 폼 컴포넌트.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-form-react-hook-form--docs",
  },
  {
    id: "input",
    name: "Input",
    description: "텍스트 입력을 받기 위한 표준 인풋 필드.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-input--docs",
  },
  {
    id: "input-group",
    name: "InputGroup",
    description: "인풋 앞뒤에 아이콘이나 텍스트를 붙이는 그룹 컴포넌트.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-inputgroup--docs",
  },
  {
    id: "input-otp",
    name: "InputOTP",
    description: "OTP 코드 입력을 위한 분할된 인풋 컴포넌트.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-inputotp--docs",
  },
  {
    id: "label",
    name: "Label",
    description: "폼 요소와 연결되는 접근성 기반의 레이블.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-label--docs",
  },
  {
    id: "radio-group",
    name: "RadioGroup",
    description: "여러 옵션 중 하나만 선택할 수 있는 라디오 버튼 그룹.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-radiogroup--docs",
  },
  {
    id: "select",
    name: "Select",
    description: "드롭다운 목록에서 단일 옵션을 선택하는 컴포넌트.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-select--docs",
  },
  {
    id: "slider",
    name: "Slider",
    description: "트랙 위를 드래그하여 범위 내 값을 선택하는 컴포넌트.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-slider--docs",
  },
  {
    id: "switch",
    name: "Switch",
    description: "On/Off 두 가지 상태를 전환하는 토글 스위치.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-switch--docs",
  },
  {
    id: "textarea",
    name: "Textarea",
    description: "여러 줄의 텍스트를 입력받는 멀티라인 인풋.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-textarea--docs",
  },
  {
    id: "toggle",
    name: "Toggle",
    description: "활성/비활성 상태를 표현하는 단일 토글 버튼.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-toggle--docs",
  },
  {
    id: "toggle-group",
    name: "ToggleGroup",
    description: "여러 토글 버튼을 하나의 그룹으로 묶어 단일/다중 선택.",
    category: "Forms",
    status: "Stable",
    path: "/?path=/docs/component-togglegroup--docs",
  },

  // ─── Layout ──────────────────────────────────────────────
  {
    id: "aspect-ratio",
    name: "AspectRatio",
    description: "자식 요소를 지정된 비율로 고정하는 레이아웃 컴포넌트.",
    category: "Layout",
    status: "Stable",
    path: "/?path=/docs/component-aspectratio--docs",
  },
  {
    id: "card",
    name: "Card",
    description: "관련 콘텐츠를 하나의 컨테이너로 묶는 카드 레이아웃.",
    category: "Layout",
    status: "Stable",
    path: "/?path=/docs/component-card--docs",
  },
  {
    id: "resizable",
    name: "Resizable",
    description: "드래그로 크기를 조절할 수 있는 패널 그룹 레이아웃.",
    category: "Layout",
    status: "Stable",
    path: "/?path=/docs/component-resizablepanelgroup--docs",
  },
  {
    id: "scroll-area",
    name: "ScrollArea",
    description: "커스텀 스크롤바를 가진 스크롤 가능 영역.",
    category: "Layout",
    status: "Stable",
    path: "/?path=/docs/component-scrollarea--docs",
  },
  {
    id: "separator",
    name: "Separator",
    description: "콘텐츠 사이를 시각적으로 구분하는 구분선.",
    category: "Layout",
    status: "Stable",
    path: "/?path=/docs/component-separator--docs",
  },
  {
    id: "sidebar",
    name: "Sidebar",
    description: "앱의 주요 네비게이션을 담는 사이드바 레이아웃.",
    category: "Layout",
    status: "Stable",
    path: "/?path=/docs/component-sidebar--docs",
  },

  // ─── Navigation ──────────────────────────────────────────
  {
    id: "breadcrumb",
    name: "Breadcrumb",
    description: "현재 페이지의 계층 경로를 보여주는 브레드크럼.",
    category: "Navigation",
    status: "Stable",
    path: "/?path=/docs/component-breadcrumb--docs",
  },
  {
    id: "menubar",
    name: "Menubar",
    description: "데스크탑 앱 스타일의 수평 메뉴바 컴포넌트.",
    category: "Navigation",
    status: "Stable",
    path: "/?path=/docs/component-menubar--docs",
  },
  {
    id: "navigation-menu",
    name: "NavigationMenu",
    description: "링크와 드롭다운을 포함한 메인 네비게이션 메뉴.",
    category: "Navigation",
    status: "Stable",
    path: "/?path=/docs/component-navigationmenu--docs",
  },
  {
    id: "pagination",
    name: "Pagination",
    description: "페이지 목록을 나눠 탐색하는 페이지네이션 컴포넌트.",
    category: "Navigation",
    status: "Stable",
    path: "/?path=/docs/component-pagination--docs",
  },
  {
    id: "tabs",
    name: "Tabs",
    description: "탭을 전환해 관련 콘텐츠 섹션을 표시하는 컴포넌트.",
    category: "Navigation",
    status: "Stable",
    path: "/?path=/docs/component-tabs--docs",
  },

  // ─── Overlay ─────────────────────────────────────────────
  {
    id: "alert-dialog",
    name: "AlertDialog",
    description: "사용자의 확인이 필요한 중요한 액션을 위한 경고 다이얼로그.",
    category: "Overlay",
    status: "Stable",
    path: "/?path=/docs/component-alertdialog--docs",
  },
  {
    id: "context-menu",
    name: "ContextMenu",
    description: "우클릭 또는 길게 눌러 표시되는 컨텍스트 메뉴.",
    category: "Overlay",
    status: "Stable",
    path: "/?path=/docs/component-contextmenu--docs",
  },
  {
    id: "dialog",
    name: "Dialog",
    description: "페이지 위에 오버레이되어 포커스를 집중시키는 모달 다이얼로그.",
    category: "Overlay",
    status: "Stable",
    path: "/?path=/docs/component-dialog--docs",
  },
  {
    id: "drawer",
    name: "Drawer",
    description: "화면 가장자리에서 슬라이드되어 나오는 드로어 패널.",
    category: "Overlay",
    status: "Stable",
    path: "/?path=/docs/component-drawer--docs",
  },
  {
    id: "dropdown-menu",
    name: "DropdownMenu",
    description: "트리거 요소 아래에 열리는 드롭다운 메뉴.",
    category: "Overlay",
    status: "Stable",
    path: "/?path=/docs/component-dropdownmenu--docs",
  },
  {
    id: "hover-card",
    name: "HoverCard",
    description: "요소에 호버 시 미리보기 정보를 표시하는 카드.",
    category: "Overlay",
    status: "Stable",
    path: "/?path=/docs/component-hovercard--docs",
  },
  {
    id: "popover",
    name: "Popover",
    description: "트리거 근처에 추가 콘텐츠를 띄우는 팝오버.",
    category: "Overlay",
    status: "Stable",
    path: "/?path=/docs/component-popover--docs",
  },
  {
    id: "sheet",
    name: "Sheet",
    description: "화면 측면에서 슬라이드되는 Dialog 변형 컴포넌트.",
    category: "Overlay",
    status: "Stable",
    path: "/?path=/docs/component-sheet--docs",
  },
  {
    id: "tooltip",
    name: "Tooltip",
    description: "요소에 호버 시 간단한 설명 텍스트를 표시.",
    category: "Overlay",
    status: "Stable",
    path: "/?path=/docs/component-tooltip--docs",
  },

  // ─── Feedback ────────────────────────────────────────────
  {
    id: "alert",
    name: "Alert",
    description: "정보, 경고, 오류 등의 상태를 인라인으로 전달하는 알림.",
    category: "Feedback",
    status: "Stable",
    path: "/?path=/docs/component-alert--docs",
  },
  {
    id: "badge",
    name: "Badge",
    description: "상태, 카운트, 레이블을 표시하는 작은 배지 컴포넌트.",
    category: "Feedback",
    status: "Stable",
    path: "/?path=/docs/component-badge--docs",
  },
  {
    id: "empty",
    name: "Empty",
    description: "데이터가 없는 빈 상태를 시각적으로 표현하는 컴포넌트.",
    category: "Feedback",
    status: "Stable",
    path: "/?path=/docs/component-empty--docs",
  },
  {
    id: "progress",
    name: "Progress",
    description: "작업 진행 상태를 시각적으로 나타내는 프로그레스 바.",
    category: "Feedback",
    status: "Stable",
    path: "/?path=/docs/component-progress--docs",
  },
  {
    id: "skeleton",
    name: "Skeleton",
    description: "콘텐츠 로딩 중 자리를 차지하는 스켈레톤 플레이스홀더.",
    category: "Feedback",
    status: "Stable",
    path: "/?path=/docs/component-skeleton--docs",
  },
  {
    id: "sonner",
    name: "Sonner",
    description: "페이지 상단에 나타나는 토스트 알림 컴포넌트.",
    category: "Feedback",
    status: "Stable",
    path: "/?path=/docs/component-sonner--docs",
  },
  {
    id: "spinner",
    name: "Spinner",
    description: "비동기 처리 중 로딩 상태를 나타내는 스피너.",
    category: "Feedback",
    status: "Stable",
    path: "/?path=/docs/component-spinner--docs",
  },

  // ─── Display ─────────────────────────────────────────────
  {
    id: "accordion",
    name: "Accordion",
    description: "클릭으로 펼치고 접을 수 있는 아코디언 섹션.",
    category: "Display",
    status: "Stable",
    path: "/?path=/docs/component-accordion--docs",
  },
  {
    id: "avatar",
    name: "Avatar",
    description: "사용자 프로필 이미지 또는 폴백 이니셜을 표시.",
    category: "Display",
    status: "Stable",
    path: "/?path=/docs/component-avatar--docs",
  },
  {
    id: "calendar",
    name: "Calendar",
    description: "월별 날짜를 탐색하고 선택하는 캘린더 컴포넌트.",
    category: "Display",
    status: "Stable",
    path: "/?path=/docs/component-calendar--docs",
  },
  {
    id: "carousel",
    name: "Carousel",
    description: "슬라이드 방식으로 콘텐츠를 순환 표시하는 캐러셀.",
    category: "Display",
    status: "Stable",
    path: "/?path=/docs/component-carousel--docs",
  },
  {
    id: "chart",
    name: "Chart",
    description: "Recharts 기반의 데이터 시각화 차트 컴포넌트.",
    category: "Display",
    status: "Stable",
    path: "/?path=/docs/component-chart--docs",
  },
  {
    id: "collapsible",
    name: "Collapsible",
    description: "콘텐츠 영역을 접고 펼칠 수 있는 콜랩서블 섹션.",
    category: "Display",
    status: "Stable",
    path: "/?path=/docs/component-collapsible--docs",
  },
  {
    id: "command",
    name: "Command",
    description: "키보드 중심의 커맨드 팔레트 및 검색 컴포넌트.",
    category: "Display",
    status: "Stable",
    path: "/?path=/docs/component-command--docs",
  },
  {
    id: "item",
    name: "Item",
    description: "리스트나 메뉴에서 단일 항목을 표현하는 기본 아이템.",
    category: "Display",
    status: "Stable",
    path: "/?path=/docs/component-item--docs",
  },
  {
    id: "kbd",
    name: "Kbd",
    description: "키보드 단축키를 시각적으로 표현하는 키 컴포넌트.",
    category: "Display",
    status: "Stable",
    path: "/?path=/docs/component-kbd--docs",
  },
  {
    id: "table",
    name: "Table",
    description: "구조화된 데이터를 행과 열로 표시하는 테이블.",
    category: "Display",
    status: "Stable",
    path: "/?path=/docs/component-table--docs",
  },
];

export const CATEGORIES: ComponentCategory[] = [
  "Forms",
  "Layout",
  "Navigation",
  "Overlay",
  "Feedback",
  "Display",
];
